### ISSUE TITLE
Run an error after the update

### ISSUE THREAD

**Issue by zhq1** [StarbuckBG/node-stratum-pool#11]
018-07-23 15:33:46 [Payments]	[bitcoinpay] Payment processing setup with daemon (geetygrpc@127.0.0.1:8379) and redis (127.0.0.1:6379)
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: bind EADDRNOTAVAIL 47.75.77.92:80
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at listenOnMasterHandle (net.js:1411:16)
    at rr (internal/cluster/child.js:111:12)
    at Worker.send (internal/cluster/child.js:78:7)
    at process.onInternalMessage (internal/cluster/utils.js:42:8)
    at emitTwo (events.js:131:20)
    at process.emit (events.js:214:7)
    at emit (internal/child_process.js:772:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
2018-07-23 15:33:46 [Master]	[Website] Website process died, spawning replacement...

**Comment by ZhiKosta** [comment]
This repo is outdated. For latest BTG Znomp check out: https://github.com/BitcoinGold-mining/z-nomp-bitcoin-gold

**Comment by zhq1** [comment]
No error will be reported when using the previous version, but it is not sure whether it is out of the block.

**Comment by TheComputerGenie** [comment]
> EADDRNOTAVAIL

 
Means that you're already using the port in the config (in this case, port 80) for something else. Change the port in config to an unused portand the error will go away.
